# Generated by Django 5.2.7 on 2025-10-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordprofile',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('M.s', 'M.s'), ('Mrs', 'Mrs')], default='Mr', max_length=5),
        ),
    ]
