# Generated by Django 5.2.7 on 2025-10-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0004_landlordprofile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('terms', 'Terms and Conditions'), ('privacy', 'Privacy Policy'), ('about', 'About Us'), ('safety', 'Safety Guidelines')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='You can use HTML tags for styling: <b>bold</b>, <i>italic</i>, <u>underline</u>, <ul><li>lists</li></ul>, <h1>-<h6> headings, etc.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Contents',
            },
        ),
    ]
