# Generated by Django 5.2.7 on 2025-10-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0005_sitecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='title',
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
