# Generated by Django 5.2.7 on 2025-10-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0006_remove_accommodation_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('triple', 'Triple+ Room')], max_length=20),
        ),
    ]
