# Generated by Django 5.2.7 on 2025-11-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='subregion',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
