# Generated by Django 5.2.7 on 2025-11-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_region_slug_subregion_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subregion',
            unique_together=set(),
        ),
    ]
