# Generated by Django 5.2.7 on 2025-11-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_alter_subregion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subregion',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='subregion',
            unique_together={('region', 'name')},
        ),
    ]
