# Generated by Django 5.2.7 on 2025-11-07 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_alter_region_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subregion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='region',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subregion',
            name='slug',
        ),
    ]
